#!/usr/bin/env bash
# Scripts that transfers a file from our client to a server

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <file_path> <server_ip> <username> <private_key_path>"
    exit 1
fi

file_path=$1
server_ip=$2
username=$3
private_key_path=$4

# Transfer the file using scp
scp -i Strict host key checking must be disabled when using scp "$private_key_path" "$file_path" "$username"@"$server_ip":~/
