#!/usr/bin/env bash
#Ping and an IP address that is pass an an argument

if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
    ping -c 5 "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP ADDRESS}"
fi
