#!/usr/bin/env bash

#Create a user and group for nginx
sudo  useradd -r -s /sbin/nologin -d var/www  user

#Change the ownership  of the nginx configuration files and directory
sudo chown -R  user:ngnix /etc/nginx /var/www

#nginx must be listening on all active IPs on port 8080
sudo vim -i 's/# listen 80;/listen 8080;/' /etc/nginx/sites-available/default
nginx_conf_content="
user user;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    ##
    # Basic Settings
    ##

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    # server_tokens off;

    server_names_hash_bucket_size 64;
    # server_name_in_redirect off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # Logging Settings
    ##

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ##
    # Gzip Settings
    ##

    gzip on;
    gzip_disable "msie6";

    # Virtual Host Configs
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
"
echo "$nginx_conf_content" | sudo tee /etc/nginx/nginx.conf > /dev/null

sudo service nginx restart
